// Core types for Cipher Pol

export interface CipherPolConfig {
  adapter: 'strk20' | 'privacy-pools';
  starknetRpcUrl?: string;
  litNetwork?: 'datil' | 'cayenne' | 'manzano';
  storachaEmail?: string;
  settlementFeeBps?: number; // default 10 (0.1%)
  /** ERC-8004 agent identity config. Enables receipt generation after payments. */
  erc8004?: {
    name: string;
    description: string;
    ethAddress?: string;
    starknetAddress?: string;
    agentId?: number;
    registryAddress?: string;
  };
}

export interface Note {
  secret: bigint;
  nullifier: bigint;
  amount: bigint;
  token: string; // contract address
  spent: boolean;
  /** Commitment hash = poseidon2(poseidon2(secret, nullifier), amount) */
  commitment: bigint;
  /** Leaf index in the pool's Merkle tree (-1 if unknown) */
  leafIndex: number;
  /** Transaction hash of the deposit (stored locally by agent, never sent to server) */
  depositTxHash?: string;
}

export interface PaymentIntent {
  url: string;
  amount: bigint;
  token: string; // 'USDC', 'STRK', or contract address
  maxLatencyMs?: number; // default 5000
}

export interface PaymentReceipt {
  txHash: string;
  timestamp: number;
  amount: bigint;
  token: string;
  apiUrl: string;
  encrypted: boolean; // stored in Storacha if true
  cid?: string;        // Filecoin CID if encrypted
}

export interface PrivacyScore {
  adapter: string;
  depositorVisible: boolean;
  proofSystem: 'groth16' | 'stark' | 'plonk';
  quantumResistant: boolean;
  anonymitySetSize: number | 'unlimited';
  guarantee: 'demo' | 'weak' | 'strong' | 'zk-native';
  recommendation?: string;
}

export interface AuditProof {
  viewingKey: string;
  payments: PaymentReceipt[];
  totalAmount: bigint;
  timeRange: { from: number; to: number };
  proof: string; // serialized ZK proof
}

// Adapter interface — every backend implements this
export interface IPrivacyAdapter {
  name: string;
  getPrivacyScore(): PrivacyScore;

  // deposit into the privacy pool / shield tokens
  deposit(amount: bigint, token: string): Promise<{ txHash: string; note: Note }>;

  // withdraw from pool / unshield tokens to recipient
  // proof: Groth16 proof felts for PrivacyPoolsAdapter (generated by AGENT, not server)
  withdraw(note: Note, recipient: string, proof?: bigint[]): Promise<{ txHash: string }>;

  // for compliance: generate audit proof
  generateAuditProof?(
    viewingKey: string,
    range: { from: number; to: number }
  ): Promise<AuditProof>;
}

// ── x402 HTTP challenge/response types ────────────────────────────────────────

export interface X402Challenge {
  scheme: string;
  network: string;
  token: string;
  amount: string;
  /** Starknet address of the API server (recipient of the ZK proof) */
  payTo: string;
  /** Address of the Ekubo privacy pool contract */
  poolAddress?: string;
  memo?: string;
}

/**
 * X-Payment-Proof header — client-side ZK proof of a deposit in the privacy pool.
 *
 * The proof commits to: recipient = API server address, amount >= required amount.
 * The server extracts public inputs to verify these commitments without seeing
 * the depositor's address or the (secret, nullifier) pair.
 *
 * Privacy properties:
 * - NO txHash: server cannot look up the depositor address
 * - NO secret/nullifier: server cannot regenerate or trace the deposit
 * - zkProof: cryptographic proof of inclusion in the pool's Merkle tree
 * - nullifierHash: public signal for double-spend prevention
 * - publicInputs: decoded public signals for server-side validation
 */
export interface X402PaymentProof {
  scheme: string;
  network: string;

  /**
   * Groth16 proof serialized as felt252 strings.
   * Format: [pi_a (4), pi_b (8), pi_c (4), public_signals (14)] = 30 felts total.
   * Pass directly to pool.withdraw() on Starknet.
   */
  zkProof: string[];

  /**
   * nullifierHash = poseidon2(nullifier, nullifier).
   * Public signal extracted from the proof. Server tracks these to prevent replay
   * before the pool contract records the spend on-chain.
   */
  nullifierHash: string;

  /**
   * Decoded public inputs for server-side validation without re-deserializing zkProof.
   * The server MUST verify: publicInputs.recipient == serverAddress, amount >= required.
   */
  publicInputs: {
    root: string;
    nullifierHash: string;
    recipient: string;
    fee: string;
    amount: string;
    refundCommitmentHash: string;
    associatedSetRoot: string;
  };

  /** ERC-8004 agent identity URI (optional) */
  agentURI?: string;
  /** ERC-8004 agent ID (optional) */
  agentId?: string;
}
